[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[colors.cursor]
cursor = "#c5c8c6"
text = "#1d1f21"

[colors.normal]
black = "#1d1f21"
red = "#cc6666"
green = "#b5bd68"
yellow = "#f0c674"
blue = "#81a2be"
magenta = "#b294bb"
cyan = "#8abeb7"
white = "#c5c8c6"

[colors.bright]
black = "#969896"
red = "#cc6666"
green = "#b5bd68"
yellow = "#f0c674"
blue = "#81a2be"
magenta = "#b294bb"
cyan = "#8abeb7"
white = "#ffffff"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "Berkeley Mono Nerd Font Mono"

[selection]
save_to_clipboard = true

[window.dimensions]
columns = 120
lines = 36

[keyboard]
bindings = [
    { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]
